import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Loader from "./components/Loader"
import Navbar from "./components/Navbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AI Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <main className="flex-grow ">{children}</main> */}

          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
              <Loader />
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-grow ">{children}</main>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
